### ISSUE TITLE
How to set up

### ISSUE THREAD

**Issue by ali-matrix22** [kunzite-app/008#27] opened 2023-12-07 23:40 UTC
Hello. Thank you for your time on this project.
I made the json file, but I don't know where to import it!
There is no upload button in the settings section! Should I copy this file to a specific path?

**Comment by ali-matrix22** [comment] 2023-12-10 11:20
is this ok?
setting:     C:\Program Files\008\config.json

**Comment by DavidGOrtega** [comment] 2023-12-11 08:25
C:/Program Files/008/config.json

This should be working but I can confirm it

**Comment by DavidGOrtega** [comment] 2023-12-11 10:14
@ali-matrix22 I can confirm that your path should work even with backslashes

**Comment by ali-matrix22** [comment] 2023-12-11 10:31
![Untitled](https://github.com/kunzite-app/008/assets/62825445/21af3bf1-b0b4-4075-89b9-01a92e4e31ff)

I took the test with both / and \ but it doesn't register. I tested with username and password and without them, but it still didn't work!
I monitored the network traffic with Wireshark, but no traffic is sent from my pc to the server!

**Comment by DavidGOrtega** [comment] 2023-12-11 10:42
@ali-matrix22 if you are pretending to do an http request with basic auth you must setup an http uri. As far as I see you are trying to do basic auth reading a file. That will not work. Just to clarify that user and password will only work to authenticate against the server that is reading the config file. Inside that config you will need to setup your sip parameters

**Comment by ali-matrix22** [comment] 2023-12-11 11:52
So I probably misunderstood what you meant!
I copied the config file to a Windows path (inside the program's installation folder) and used the Windows address, which was not registered with this method.
It cannot be connected through the following address, which requires authentication.
http://myhost.com/var/www/html/app008/config.json
Do I need to set up an FTP server or TFTP server?
Is it not possible to specify this path through the local path of the Windows client?

**Comment by DavidGOrtega** [comment] 2023-12-11 15:25
> I copied the config file to a Windows path (inside the program's installation folder) and used the Windows address, which was not registered with this method.

You can of course use a local file as we stated before. However Im not sure whats the basic auth that you have filled. Its that by any meaning your sip user? 

Here are the steps:

1 Edit your config.json file locally. Lets say C:\config.json. The minimum parameters to login `sipUri`, `sipPassword` and `wsUri`. You might need to setup your `sipUser` in case that your sip provider need it.

```json
"sipUri": "sip:johndoe@example.com",
"sipPassword": "yoursippass",
"wsUri": "wss://asterisk.example.com:8089/ws",
```

2. Put the uri location in the settings 

<img width="329" alt="image" src="https://github.com/kunzite-app/008/assets/414967/2e1261d4-c36b-4092-ae58-222aba8286bd">

Please note that we are not specifying any Basic Auth here since file do not need it. Its just loading a file.

Please let me know if this helps 🙏

**Comment by ali-matrix22** [comment] 2023-12-12 08:07
I followed your method and used the C:\config.json path, but still nothing happens, and using Wireshark monitoring, it is quite clear that no request is sent from the soft phone to the server!
The point is that when I close the softphone program and open it again, all the previous settings are deleted!
my config file is:
  "sipUri": "sip:8801@10.1.15.70",
  "sipPassword": "0e6b61119hgvchgghcd10c735d98a1ce",
  "sipUser": "8801",
  "wsUri": "wss://10.1.10.70:8089/ws",

**Comment by DavidGOrtega** [comment] 2023-12-12 09:22
@ali-matrix22 there are issues with your socket, I can see this in the stacktrace:

```
Tue Dec 12 2023 10:19:23 GMT+0100 (Central European Standard Time) | sip.transport | · wsServers: [{"wsUri":"wss://EDITED:8089/ws","sipUri":"<sip:EDITED:8089;transport=ws;lr>","weight":0,"isError":false,"scheme":"WSS"}]
```

```
Tue Dec 12 2023 10:19:23 GMT+0100 (Central European Standard Time) | sip.transport | connecting to WebSocket wss://EDITED:8089/ws
logger-factory.js:95 Tue Dec 12 2023 10:19:23 GMT+0100 (Central European Standard Time) | sip.transport | Attempting to transition status from 0 to 3
logger-factory.js:91 Tue Dec 12 2023 10:19:23 GMT+0100 (Central European Standard Time) | sip.transport | took too long to connect - exceeded time set in configuration.connectionTimeout: 5s
LoggerFactory.print @ logger-factory.js:91
LoggerFactory.genericLog @ logger-factory.js:69
Logger.genericLog @ logger.js:19
Logger.warn @ logger.js:15
(anonymous) @ Transport.js:169
setTimeout (async)
(anonymous) @ Transport.js:167
Transport.connectPromise @ Transport.js:135
Transport.connect @ Transport.js:46
UA.start @ UA.js:394
(anonymous) @ index.js:239
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ index.js:141
localhost/:1 Uncaught (in promise) Connection timeout
```

However this might not explain why you do not see traffic at all

**Comment by DavidGOrtega** [comment] 2023-12-13 20:22
@ali-matrix22 were you able to find out the wss issue?

**Comment by ali-matrix22** [comment] 2023-12-18 15:51
> @ali-matrix22 which OS version are you using? This sound like a firewall, permissions issue, maybe?

Windows 10  &  Windows 11

**Comment by ali-matrix22** [comment] 2023-12-18 15:58
> were you able to find out the wss issue?

Unfortunately no. Apparently everything is right! I have to install a new server and test again.
My server can't connect to the internet, so I have to use a self-signed certificate.

**Comment by DavidGOrtega** [comment] 2023-12-19 08:48
@ali-matrix22 can you try the `ws` protocol? Asterisk runs `ws` in another port.
Also, have you check that you have TSL enabled in wireshark? That might be the reason why you do not capture any traffic 🤔

**Comment by ali-matrix22** [comment] 2023-12-19 10:45
Asterisk also uses "ws" protocol exactly on port 8089.

**Comment by DavidGOrtega** [comment] 2023-12-19 10:53
It does not work if you specify `ws:` ? In the settings that you passed to me is `wss`. Im going to check also.

**Comment by DavidGOrtega** [comment] 2023-12-20 10:01
@ali-matrix22 I have tried ws and wss andf your socket seems to be down

```
logger-factory.js:91 Wed Dec 20 2023 11:00:01 GMT+0100 (Central European Standard Time) | sip.transport | took too long to connect - exceeded time set in configuration.connectionTimeout: 5s

Transport.js:179 WebSocket connection to 'wss://10.1.10.70:8089/ws' failed: WebSocket is closed before the connection is established.

Uncaught (in promise) Connection timeout
```

**Comment by ali-matrix22** [comment] 2023-12-30 07:47
No, this service is not stopped, but maybe the firewall is blocking it! The following ports are all open on the firewall:
5060 UDP
10000 to 20000 UDP
443 TCP
8089 TCP

**Comment by DavidGOrtega** [comment] 2024-12-19 18:30
closing. please feel free if you have any other issue.

**Closed by DavidGOrtega** 2024-12-19 18:30 UTC
Labels: documentation
